events { worker_connections 1024; }

http {
  sendfile on;
  tcp_nopush on;
  keepalive_timeout 65;
  client_header_buffer_size 16k;
  large_client_header_buffers 4 32k;

  # HTTP → redirige a HTTPS
  server {
    listen 80;
    server_name n8n.kinforgeworks.com;

    location /.well-known/acme-challenge/ {
      root /var/www/certbot;
    }

    location / {
      return 301 https://$host$request_uri;
    }
  }

  # HTTPS → proxy a n8n
  server {
    listen 443 ssl;
    server_name n8n.kinforgeworks.com;

    ssl_certificate     /etc/letsencrypt/live/n8n.kinforgeworks.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/n8n.kinforgeworks.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
      proxy_pass http://n8n:5678;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # Websockets
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }

  ########################################################################
  # European Masters: landing + backend
  ########################################################################

  # HTTP → redirige a HTTPS (European Masters)
  server {
      listen 80;
      server_name european-masters-web.kinforgeworks.com;

          location / {
             proxy_pass http://em-web:80;    # nombre del servicio en kinForge-net
             proxy_set_header Host $host;
             proxy_set_header X-Real-IP $remote_addr;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_set_header X-Forwarded-Proto $scheme;
         }
  }

  # HTTPS → proxy a landing (/) y backend (/api)
  server {
    listen 443 ssl;
    server_name masters.kinforgeworks.com;

    ssl_certificate     /etc/letsencrypt/live/masters.kinforgeworks.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/masters.kinforgeworks.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # Backend Spring Boot (em-backend)
    location /api/ {
      proxy_pass http://em-backend:8080/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
