version = 5.4.0
archive_dir = /etc/letsencrypt/archive/n8n.kinforgeworks.com
cert = /etc/letsencrypt/live/n8n.kinforgeworks.com/cert.pem
privkey = /etc/letsencrypt/live/n8n.kinforgeworks.com/privkey.pem
chain = /etc/letsencrypt/live/n8n.kinforgeworks.com/chain.pem
fullchain = /etc/letsencrypt/live/n8n.kinforgeworks.com/fullchain.pem
[renewalparams]
account = 30fbd930c8ad5c3851fe2a65cf17193a
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
n8n.kinforgeworks.com = /var/www/certbot
