name: Deploy Componentes Específicos

on:
  push:
    branches:
      - master
    # AQUÍ ESTÁ EL TRUCO: Solo se activa si cambias archivos en estas carpetas
    paths:
      - 'european-masters/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # ESTO ES LO QUE FALTA:
    environment: works
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Desplegar en Contabo vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ vars.SSH_USER }}  # Si está en la pestaña "Variables"
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/bob/projects/KindredWorks/
            git pull origin master
            cd european-masters

            # Pasamos los secrets de GitHub como variables de entorno al comando
            export SMTP_USER=${{ secrets.AWS_SMTP_USER }}
            export SMTP_PASS=${{ secrets.AWS_SMTP_PASS }}
            
            # Forzamos la reconstrucción si cambiaste el código Java
            # y levantamos en segundo plano (-d)
            podman-compose down
            podman-compose up --build -d
            
            # Limpieza de imágenes huérfanas para ahorrar espacio en Contabo
            podman image prune -f
