name: Deploy Componentes Específicos

on:
  push:
    branches:
      - master
    # AQUÍ ESTÁ EL TRUCO: Solo se activa si cambias archivos en estas carpetas
    paths:
      - 'european-masters/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # ESTO ES LO QUE FALTA:
    environment: works
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Desplegar en Contabo vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "HOST_B64: $(echo -n '${{ secrets.SSH_HOST }}' | base64)"
            echo "USER_B64: $(echo -n '${{ secrets.SSH_USER }}' | base64)"
            cd /home/bob/projects/KindredWorks/european-masters
            git pull origin master
